---
json_rpc_url: http://api.devnet.solana.com
update_manifest_pubkey:
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
current_update_manifest: null
update_poll_secs: 3600
explicit_release: !Semver 1.17.16
releases_dir: C:\Users\suksh\.local\share\solana\install\releases
active_release_dir: C:\Users\suksh\.local\share\solana\install\active_release
